# Generated by Django 3.1.6 on 2021-02-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('org_name', models.CharField(max_length=256)),
                ('yoe', models.IntegerField()),
                ('mail_id', models.CharField(max_length=32)),
            ],
        ),
    ]
