# Generated by Django 3.1.6 on 2021-02-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishdate', models.DateField()),
                ('title', models.CharField(max_length=256)),
                ('link', models.URLField()),
                ('author', models.CharField(max_length=32)),
                ('tags', models.CharField(max_length=256)),
            ],
        ),
    ]
