# Generated by Django 3.1.6 on 2021-02-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=32)),
                ('StartTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField()),
                ('IsAllDay', models.BooleanField()),
            ],
        ),
    ]
